# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Misato O.
email: misato@mokutsu.com
subtitle: Hi my name is Misato Okutsu and I am a web developer in the Toronto, ON area.
description: Hi my name is Misato Okutsu and I am a web developer in the Toronto, ON area.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mokutsu.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: mokutsu2
github_username:  mokutsu

# Build settings
markdown: kramdown

gems: [jekyll-paginate]

paginate: 5
paginate_path: "/_posts"
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
